# Configurations
title:            망고는 코딩대장
longtitle:        프론트엔트 스터디룸
author:           김망고네 강아지 김경아
email:            qwerewqwerew@gmail.com
description: >
  프론트엔드 프로그래밍 언어를 주제로 공부해요

version:          1.0
gitbook_version:  3.2.3

url:              'https://qwerewqwerew.github.io/book01'
#baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  dinosaur.gif:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: base16.dark

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts
  - _pages

collections:
  pages:
    output: false
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

tracker:
  google_analytics: "<YOUR GOOGLE ANALYTICS KEY, e.g, G-VLV52W1RFQ>"  
#https://jekyllrb-ko.github.io/
#gem install bundler jekyll
#jekyll new my-blog
#cd my-blog
#bundle exec jekyll serve
# => 브라우저로 http://localhost:4000 에 접속